# Generated by Django 5.2 on 2025-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this teacher belongs to.', related_name='teacher_groups', related_query_name='teacher', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this teacher.', related_name='teacher_user_permissions', related_query_name='teacher', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
